student@guithi0777-server:~/ansible-test$ cat playbooks/recette.yml 

- name: toto.txt
  hosts: ansible-test
  remote_user: root

  tasks:
    - name: create empty toto.txt file
      ansible.builtin.file:
        path: /etc/toto.txt
        state: touch

    - name: install needed packages
      ansible.builtin.apt:
        name: cowsay
        state: present
        update_cache: yes

    - name: run a specific command
      ansible.builtin.shell:
        cmd: cowsay "hello DevOps"
